// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'vi'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	routes: {
		root: {
			/**
			 * T​r​a​n​g​ ​c​h​í​n​h
			 */
			layout: string
		}
	}
}

export type TranslationFunctions = {
	routes: {
		root: {
			/**
			 * Trang chính
			 */
			layout: () => LocalizedString
		}
	}
}

export type Formatters = {}
