/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Char123LocaleChar125HelloRouteImport } from './routes/{-$locale}/hello'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125HelloRoute =
  Char123LocaleChar125HelloRouteImport.update({
    id: '/hello',
    path: '/hello',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/hello': typeof Char123LocaleChar125HelloRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/hello': typeof Char123LocaleChar125HelloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/hello': typeof Char123LocaleChar125HelloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/{-$locale}'
    | '/dashboard/users'
    | '/{-$locale}/404'
    | '/{-$locale}/hello'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/{-$locale}'
    | '/dashboard/users'
    | '/{-$locale}/404'
    | '/{-$locale}/hello'
  id:
    | '__root__'
    | '/dashboard'
    | '/{-$locale}'
    | '/dashboard/users'
    | '/{-$locale}/404'
    | '/{-$locale}/hello'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/hello': {
      id: '/{-$locale}/hello'
      path: '/hello'
      fullPath: '/{-$locale}/hello'
      preLoaderRoute: typeof Char123LocaleChar125HelloRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardUsersRoute: typeof DashboardUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardUsersRoute: DashboardUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125HelloRoute: typeof Char123LocaleChar125HelloRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125404Route: Char123LocaleChar125404Route,
  Char123LocaleChar125HelloRoute: Char123LocaleChar125HelloRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
